education_portal/authy/urls.py
from django.urls import path
from django.contrib.auth import views as authViews 

from authy.views import (
    sign_up,
    change_password,
    password_change_done,
    profile,
)

urlpatterns = [
    path('profile', profile, name='profile'),
   	path('auth/signup', sign_up, name='sign-up'),
   	path('auth/login', authViews.LoginView.as_view(template_name='registration/login.html'), name='login'),
   	path('auth/logout', authViews.LogoutView.as_view(), {'next_page' : 'index'}, name='logout'),
   	path('password/change', change_password, name='change-password'),
   	path('password/change/done', password_change_done, name='password-change-done'),
   	path('password/reset', authViews.PasswordResetView.as_view(), name='password-reset'),
   	path('password/reset/done', authViews.PasswordResetDoneView.as_view(), name='password-reset-done'),
   	path('password/reset/<uidb64>/<token>', authViews.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
   	path('password/reset/complete', authViews.PasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

education_portal/education_portal/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from classroom.views import index

urlpatterns = [
    path("", index, name="index"),
    path("", include("authy.urls")),
    path("admin", admin.site.urls),
    path("statistics", include("user_statistics.urls")),
    path("courses/", include("classroom.urls")),
    path("control/", include("learningcontrol.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education_portal/quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Answer(models.Model):
    answer_text = models.CharField(max_length=900)
    is_correct = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_text


class Question(models.Model):
    question_text = models.CharField(max_length=900)
    answers = models.ManyToManyField(Answer)
    points = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text


class Quizzes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = RichTextField()
    questions = models.ManyToManyField(Question)
    points_to_pass = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.title


class Attempter(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quizzes, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    test_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Attempt(models.Model):
    quiz = models.ForeignKey(Quizzes, on_delete=models.CASCADE)
    attempter = models.ForeignKey(Attempter, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    def __str__(self):
        return self.attempter.user.username + " - " + self.answer.answer_text

education_portal/quiz/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from quiz.models import Quizzes, Question, Answer


class NewQuizForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={"class": "validate"}),
        required=True,
    )
    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Quizzes
        fields = ("title", "description")


class NewQuestionForm(forms.ModelForm):
    question_text = forms.CharField(
        widget=forms.TextInput(attrs={"class": "validate"}),
        required=True,
    )

    class Meta:
        model = Question
        fields = ("question_text",)


class QuizDetailForm(forms.ModelForm):
    class Meta:
        model = Quizzes
        fields = ["points_to_pass"]
        labels = {
            "points_to_pass": "",
        }
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            max_score = self.instance.questions.count()  # get questions count
            self.fields['points_to_pass'].widget.attrs['min'] = 1
            self.fields['points_to_pass'].widget.attrs['max'] = max_score

education_portal/quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.urls import reverse

from quiz.forms import NewQuizForm, NewQuestionForm, QuizDetailForm
from quiz.models import Answer, Question, Quizzes, Attempter, Attempt
from module.models import Module
from classroom.models import Course
from authy.models import Profile

from datetime import datetime


def new_test(request, course_id):
    if request.user.profile.role.name != 'admin' and request.user.is_staff == False:
        return redirect("index")

    user = request.user
    course = get_object_or_404(Course, id=course_id)
    if request.method == "POST":
        form = NewQuizForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            description = form.cleaned_data.get("description")
            quiz = Quizzes.objects.create(
                user=user, title=title, description=description
            )
            course.quizzes.add(quiz)
            course.save()
            return redirect("new-question", course_id=course_id, quiz_id=quiz.id)
    else:
        form = NewQuizForm()

    context = {
        "form": form,
    }

    return render(request, "quiz/newquiz.html", context)


def new_question(request, course_id, quiz_id):
    if request.user.profile.role.name != 'admin' and request.user.is_staff == False:
        return redirect("index")
        
    user = request.user
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    if request.method == "POST":
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data.get("question_text")
            points = 1
            answer_text = request.POST.getlist("answer_text")
            is_correct = request.POST.getlist("is_correct")
            question = Question.objects.create(
                question_text=question_text, user=user, points=points
            )

            for a, c in zip(answer_text, is_correct):
                answer = Answer.objects.create(answer_text=a, is_correct=c, user=user)
                question.answers.add(answer)
                question.save()
                quiz.questions.add(question)
                quiz.save()
            return redirect("new-question", course_id=course_id, quiz_id=quiz.id)
    else:
        form = NewQuestionForm()

    context = {
        "form": form,
        "quiz_id": quiz_id,
        "course_id": course_id,
    }

    return render(request, "quiz/newquestion.html", context)


def quiz_detail(request, course_id, quiz_id):
    profile = Profile.objects.get(user__id=request.user.id)
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    my_attempts = Attempter.objects.filter(quiz=quiz, user=request.user)
    max_score = sum(question.points for question in quiz.questions.all())

    if request.method == "POST":
        form = QuizDetailForm(request.POST, instance=quiz)
        if form.is_valid():
            form.save()
            return redirect("quiz-detail", course_id=course_id, quiz_id=quiz_id)
    else:
        form = QuizDetailForm(instance=quiz)

    context = {
        "quiz": quiz,
        "my_attempts": my_attempts,
        "course_id": course_id,
        "max_score": max_score,
        "profile": profile,
        "scores": range(1, max_score),
        "form": form,
    }

    return render(request, "quiz/quizdetail.html", context)


def take_quiz(request, course_id, quiz_id):
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    profile = Profile.objects.get(user__id=request.user.id)

    context = {
        "quiz": quiz,
        "course_id": course_id,
        "profile": profile,
    }

    return render(request, "quiz/takequiz.html", context)


def submit_attempt(request, course_id, quiz_id):
    if request.user.profile.role.name != 'user':
        return redirect("index")

    quiz = get_object_or_404(Quizzes, id=quiz_id)
    if request.method == "POST":
        questions = request.POST.getlist("question")
        answers = request.POST.getlist("answer")
        attempter = Attempter.objects.create(user=request.user, quiz=quiz, score=0)

        questions_number = len(questions)
        resolved_questions_number = 0

        # check answer for correctness
        for q, a in zip(questions, answers):
            question = Question.objects.get(id=q)
            answer = Answer.objects.get(id=a)

            # create attempt
            Attempt.objects.create(
                quiz=quiz, attempter=attempter, question=question, answer=answer
            )

            # if answer is correct, increase counter
            if answer.is_correct:
                resolved_questions_number += 1

        # mark course as completed and set completion time if
        # count of doned answer equal to total answers count
        if quiz.points_to_pass:
            questions_number = quiz.points_to_pass
        if resolved_questions_number >= questions_number:
            profile = Profile.objects.get(user=request.user)
            course = get_object_or_404(Course, id=course_id)
            current_assigned_course = profile.assigned_courses.filter(course=course).first()

            if current_assigned_course:
                current_assigned_course.is_completed = True
                current_assigned_course.completion_date = datetime.now()
                current_assigned_course.save()

            attempter.test_completed = True
            attempter.save()

        # set score of attempter, if score is equal to amount of doned questions
        attempter.score = resolved_questions_number
        attempter.save()

        return redirect(
            reverse("quiz-detail", kwargs={"course_id": course_id, "quiz_id": quiz_id})
        )


def attempt_detail(request, course_id, module_id, quiz_id, attempt_id):
    if request.user.profile.role.name != 'user':
        return redirect("index")

    user = request.user
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    attempts = Attempt.objects.filter(quiz=quiz, attempter__user=user)

    context = {
        "quiz": quiz,
        "attempts": attempts,
        "course_id": course_id,
    }

    return render(request, "quiz/attemptdetail.html", context)


def course_test(request, course_id):
    user = request.user
    course = get_object_or_404(Course, id=course_id)

    teacher_mode = False
    if user == course.user:
        teacher_mode = True

    context = {
        "teacher_mode": teacher_mode,
        "course": course,
    }

    return render(request, "quiz/quiz.html", context)

education_portal/education_portal/templates/quiz/attemptdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section ">
    <h4>{{ quiz.title }}</h4>
    <div class="divider"></div>
</div>

<div class="row">

    <div class="col s4">
        <h5>Срок:</h5>
        <p>{{ quiz.due }}</p>
    </div>

    <div class="col s4">
        <h5>Всего попыток:</h5>
        <p>{{ quiz.allowed_attempts }}</p>
    </div>

    <div class="col s4">
        <h5>Всего времени (минуты):</h5>
        <p>{{ quiz.time_limit_mins }}</p>
    </div>

    <div col s12>
        {{ quiz.description | safe }}
    </div>

    <div class="col s12">
        <form method="post" class="col s12">
            {% csrf_token %}
            {% for question in quiz.quiestions.all %}
            <div class="col s12">
                <br>
                <p>{{ question.question_text }}</p>
                <input type="hidden" name="question" value="{{ question.id }}">
            </div>

            {% for answer in question.answers.all %}
            <div class="input col s12">
                <label>
                    <input name="answer" type="checkbox" value="{{ answer.id }}" {% if answer.is_correct==True
                        %}checked="checked" {% endif %} />
                    <span>{{ answer.answer_text }}</span>
                </label>
            </div>
            {% endfor %}
            {% endfor %}
            <div class="col s12">
            </div>
        </form>
    </div>

    <div class="section ">
        <h5>Ваши ответы</h5>
        <div class="divider"></div>
        {% for attempt in attempts %}
        <h5 class="{% if attempt.answer.is_correct == True %}green{% else %}red{% endif %}-text"><b>{{
                attempt.answer.answer_text }}</b>
        </h5>
        {% endfor %}
    </div>

</div>
{% endblock %}

education_portal/education_portal/templates/quiz/newquestion.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row center-align">
    <div class="col s12">
        <form method="post" enctype="multipart/form-data" action="" role="form">
            {% csrf_token %}
            <h5>Добавить вопрос</h5>

            <div class="input-field col s12">
                <p class="left" style="margin: 0;">Вопрос</p>
                {{ form.question_text }}
            </div>

            <!-- 1 answer field -->
            <div class="input-field col s9">
                <p class="left" style="margin: 0;">Ответ 1</p>
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
            </div>

            <!-- 1 answer choice field -->
            <div class="input-field col s3">
                <p class="left grey-text" style="margin: 0;">Этот ответ верный?</p>
                <select id="id_is_correct" name="is_correct">
                    <option value="" disabled selected>Выбрать</option>
                    <option value="True">Да</option>
                    <option class="" value="False">Нет</option>
                </select>
            </div>

            <!-- 2 answer field -->
            <div class="input-field col s9">
                <p class="left" style="margin: 0;">Ответ 2</p>
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
            </div>

            <!-- 2 answer choice field -->
            <div class="input-field col s3">
                <p class="left grey-text" style="margin: 0;">Этот ответ верный?</p>
                <select id="id_is_correct" name="is_correct">
                    <option value="" disabled selected>Выбрать</option>
                    <option value="True">Да</option>
                    <option value="False">Нет</option>
                </select>
            </div>

            <!-- 3 answer field -->
            <div class="input-field col s9">
                <p class="left" style="margin: 0;">Ответ 3</p>
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
            </div>

            <!-- 3 answer choice field -->
            <div class="input-field col s3">
                <p class="left grey-text" style="margin: 0;">Этот ответ верный?</p>
                <select id="id_is_correct" name="is_correct">
                    <option value="" disabled selected>Выбрать</option>
                    <option value="True">Да</option>
                    <option value="False">Нет</option>
                </select>
            </div>

            <!-- 4 answer field -->
            <div class="input-field col s9">
                <p class="left" style="margin: 0;">Ответ 4</p>
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
            </div>

            <!-- 4 answer choice field -->
            <div class="input-field col s3">
                <p class="left grey-text" style="margin: 0;">Этот ответ верный?</p>
                <select id="id_is_correct" name="is_correct">
                    <option value="" disabled selected>Выбрать</option>
                    <option value="True">Да</option>
                    <option value="False">Нет</option>
                </select>
            </div>

            <div class="row">
                <div class="col s12">
                    <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
                </div>
            </div>

            <div class="col s12">
                <p class="control">
                    <button type="submit" value="login" class="btn green darken-1">
                        Добавить
                    </button>
                </p>
            </div>

            <div class="col s12">
                <a class="btn red darken-1" href="{% url 'take-quiz' course_id quiz_id %}">Назад</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

education_portal/education_portal/templates/quiz/newquiz.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row center-align">
    <div class="col s12">
        <form method="post" enctype="multipart/form-data" action="" role="form">
            {% csrf_token %}
            <h4 class="title is-3">Создание нового теста</h4>

            <div class="input-field col s12">
                <p class="left" style="margin: 0;">Название</p>
                {{ form.title }}
            </div>
            Описание
            <div class="input-field col s12">
                {{ form.description }}
            </div>

            <div class="row">
                <div class="col s12">
                    <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
                </div>
            </div>

            <div class="field">
                <p class="control">
                    <button type="submit" value="login" class="btn green darken-1">
                        Сохранить
                    </button>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

education_portal/education_portal/templates/quiz/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section">
    <h5>{{ course.title }}</h5>
    <div class="divider"></div>
</div>

<div class="row">
    <div class="col s3">
        <ul class="collection with-header">
            <li class="collection-header">
                <h6>Разделы</h6>
            </li>
            <a href="{% url 'course' course.id %}"
                class="collection-item darken-4 black-text text-darken-4">Описание</a>
            <a href="{% url 'modules' course.id %}" class="collection-item black-text text-darken-4">Содержание</a>
            <a href="{% url 'course-test' course.id %}" class="collection-item light-blue-text text-darken-4">
                <span style="font-weight: 500;">Тест</span>
            </a>
        </ul>
    </div>

    <div class="col s9">
        {% if teacher_mode == True and course.quizzes.all.count == 0 %}
        <a href="{% url 'new-quiz' course.id %}" class="btn-small green darken-1 right">
            Добавить тест
        </a>
        {% endif %}

        <h6 class="left-align">Тест</h6>
        <div class="divider"></div>

        <div class="collection">
            {% for quiz in course.quizzes.all %}
            <a href="{% url 'quiz-detail' course.id quiz.id %}" class="collection-item blue-text text-darken-4">
                {{ quiz.title }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

education_portal/education_portal/templates/quiz/quizdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section">
    {% if profile.role.name != 'user' %}
    <a href="{% url 'take-quiz' course_id quiz.id %}" class="btn green darken-1 right">
        <span>Редактировать вопросы</span>
    </a>
    {% endif %}
    <h5>{{ quiz.title }}</h5>
    <div class="divider"></div>
</div>
{{ quiz.description | safe }}



{% if profile.role.name == 'user' %}
<blockquote style="border-left-color: blue;">
    <span>Всего вопросов в тесте: <span style="font-weight: 500;">{{ max_score }}</span></span>
    <br>
    <span>
        Чтобы сдать тест, ответьте минимум на 
        <span style="font-weight: 500;">
            {% if quiz.points_to_pass %}
            {{ quiz.points_to_pass }}
            {% else %}
            {{ max_score }}
            {% endif %}
        </span>
        из них
    </span>
</blockquote>

<table class="highlight">
    <thead>
        <tr>
            <th style="font-weight: 600;">Попытки</th>
            <th style="font-weight: 600;">Баллы</th>
            <th style="font-weight: 600;">Результат</th>
        </tr>
    </thead>
    <tbody>
        {% for attempt in my_attempts %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ attempt.score }} из {{ max_score }}</td>
            <td>
                {% if attempt.test_completed %}
                <span class="green-text text-darken-1">Пройден</span>
                {% else %}
                <span class="red-text text-darken-1">Не пройден</span>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<br>
<a class="btn green darken-1" href="{% url 'take-quiz' course_id quiz.id %}">Пройти тест</a>
{% endif %}

{% if profile.role.name != 'user' %}
<div class="divider"></div>
<br>

<span style="font-weight: 500;">Количество вопросов:</span>
<span>{{ max_score }}</span>

<br>
<br>

<span style="font-weight: 500;">Количество правильных ответов для сдачи теста:</span>
<div class="row">
    <div class="col s1" style="padding: 0;">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn green darken-1 center">Сохранить</button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

education_portal/education_portal/templates/quiz/takequiz.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h5>{{ quiz.title }}</h5>

<form method="post" action="{% url 'submit-quiz' course_id quiz.id %}" role="form" class="col s12">
    {% csrf_token %}
    {% for question in quiz.questions.all %}
    <div class="col s12">
        <p style="font-weight: 600;">{{ question.question_text }}</p>
        <input type="hidden" name="question" value="{{ question.id }}">
    </div>

    {% for answer in question.answers.all %}
    <div class="input col s12">
        <label>
            <input name="answer" type="checkbox" value="{{ answer.id }}" />
            <span class="black-text">{{ answer.answer_text }}</span>
        </label>
    </div>
    {% endfor %}
    <br>
    {% endfor %}

    <div class="col s12">
        <div class="divider"></div>
        <br>

        {% if profile.role.name == 'user' %}
        <div>
            <button type="submit" value="login" class="btn green darken-1">
                Завершить тест
            </button>
        </div>
        {% else %}
        <a href="{% url 'quiz-detail' course_id quiz.id %}" class="btn red darken-1">
            Назад
        </a>

        <a href="{% url 'new-question' course_id quiz.id %}" class="btn green darken-1">
            Добавить вопрос
        </a>
        {% endif %}
    </div>
</form>
</div>
{% endblock %}